<?php

namespace Database\Seeders;

use App\Models\Article\Article;
use Illuminate\Database\Seeder;

class ArticleSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Article::create([
            'title' => 'Parfume untuk Wanita',
            'body' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam eleifend magna id nisi lacinia, et interdum justo egestas. Pellentesque massa arcu, dapibus vel sodales at, aliquam ac tellus. Nulla interdum rhoncus sem ac mollis. Vestibulum quis ex nulla. Morbi et felis et quam pellentesque dapibus ac vitae dolor. In non sapien metus. Sed posuere interdum quam, vitae laoreet neque pellentesque id. Quisque non orci sed neque tincidunt pulvinar eget sed mauris. Vivamus lobortis, nisl lacinia feugiat imperdiet, nunc urna luctus lectus, quis lacinia urna nibh eu magna. Nullam dapibus libero non quam pellentesque, consectetur vulputate quam placerat. Aliquam erat volutpat. Maecenas tincidunt, justo at scelerisque lacinia, arcu nibh ultrices neque, in consectetur eros tellus at orci. In orci magna, auctor in maximus id, tempor vel ipsum.
            In sapien nisl, pellentesque id bibendum vel, maximus a mauris. Curabitur efficitur elementum tincidunt. Nullam feugiat erat sed pretium gravida. Quisque aliquam nunc eros, ac tristique neque sollicitudin ut. Morbi in mi neque. Proin lectus elit, accumsan vel libero id, dictum gravida libero. Cras ultricies et purus laoreet varius. Integer velit dolor, vestibulum ac sagittis non, dapibus lobortis lorem. Cras et ornare magna. Curabitur tincidunt ac libero a lobortis. In hendrerit enim tellus, ac imperdiet lectus volutpat at. Nunc rutrum convallis ligula quis malesuada.
            Aliquam neque ligula, viverra quis metus et, scelerisque auctor leo. Nullam felis mi, ornare et commodo sed, consequat non est. Mauris placerat dignissim elit vel condimentum. Nulla a porta sapien, vitae tristique metus. Fusce iaculis nunc fringilla massa congue pharetra. Nullam eu quam euismod orci dictum bibendum non eget velit. Suspendisse potenti. Cras consequat ex at iaculis tempus. Proin lacus est, molestie vestibulum euismod et, rhoncus et neque. Maecenas venenatis risus sit amet est efficitur sollicitudin. Morbi eu ante id nunc scelerisque ultricies vitae vitae sapien.
            Ut congue tristique lacus quis molestie. Nullam lacus turpis, porta a velit quis, maximus tristique ipsum. Vivamus non pharetra eros. Sed vitae felis dolor. Curabitur et fermentum lacus. Mauris vel malesuada mi. Donec bibendum mauris quis tellus aliquam, ac mattis leo ultricies. Vestibulum metus lacus, scelerisque vel tempus ac, cursus in erat. Sed fermentum justo ac nulla molestie, accumsan malesuada velit ultrices. Morbi condimentum leo id lobortis facilisis. Donec convallis dui ante, at rutrum metus faucibus a. In a sagittis purus, ut euismod nunc.
            Nam eu ipsum diam. Nulla ipsum turpis, euismod eu dolor nec, molestie eleifend tellus. In dictum turpis a sapien dapibus, nec semper libero consequat. Vestibulum ut condimentum massa. Sed eu diam tincidunt lacus luctus bibendum. Mauris sit amet orci nulla. Nulla sed tempor dui. Nulla nunc metus, tincidunt sed mi nec, viverra porttitor mauris. Sed ut lacus quam. Aliquam felis metus, varius in pretium id, lacinia at lacus. Curabitur consequat tellus vel tortor rutrum sollicitudin. Nulla facilisi. Maecenas imperdiet neque vel volutpat imperdiet. Mauris condimentum vulputate vulputate. Praesent feugiat sit amet lectus tincidunt dictum. Aliquam tempor venenatis lorem, sit amet egestas ipsum ullamcorper rhoncus.',
            'slug' => 'parfume-untuk-wanita',
            'excerpt' => 'lorem ipsum dolor sit amet constectur lorem ipsum dolor sit amet constectur lorem ipsum dolor sit amet constectur',
            'category_id' => 1
        ]);
        Article::create([
            'title' => 'Parfume untuk Pria',
            'body' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam eleifend magna id nisi lacinia, et interdum justo egestas. Pellentesque massa arcu, dapibus vel sodales at, aliquam ac tellus. Nulla interdum rhoncus sem ac mollis. Vestibulum quis ex nulla. Morbi et felis et quam pellentesque dapibus ac vitae dolor. In non sapien metus. Sed posuere interdum quam, vitae laoreet neque pellentesque id. Quisque non orci sed neque tincidunt pulvinar eget sed mauris. Vivamus lobortis, nisl lacinia feugiat imperdiet, nunc urna luctus lectus, quis lacinia urna nibh eu magna. Nullam dapibus libero non quam pellentesque, consectetur vulputate quam placerat. Aliquam erat volutpat. Maecenas tincidunt, justo at scelerisque lacinia, arcu nibh ultrices neque, in consectetur eros tellus at orci. In orci magna, auctor in maximus id, tempor vel ipsum.
            In sapien nisl, pellentesque id bibendum vel, maximus a mauris. Curabitur efficitur elementum tincidunt. Nullam feugiat erat sed pretium gravida. Quisque aliquam nunc eros, ac tristique neque sollicitudin ut. Morbi in mi neque. Proin lectus elit, accumsan vel libero id, dictum gravida libero. Cras ultricies et purus laoreet varius. Integer velit dolor, vestibulum ac sagittis non, dapibus lobortis lorem. Cras et ornare magna. Curabitur tincidunt ac libero a lobortis. In hendrerit enim tellus, ac imperdiet lectus volutpat at. Nunc rutrum convallis ligula quis malesuada.
            Aliquam neque ligula, viverra quis metus et, scelerisque auctor leo. Nullam felis mi, ornare et commodo sed, consequat non est. Mauris placerat dignissim elit vel condimentum. Nulla a porta sapien, vitae tristique metus. Fusce iaculis nunc fringilla massa congue pharetra. Nullam eu quam euismod orci dictum bibendum non eget velit. Suspendisse potenti. Cras consequat ex at iaculis tempus. Proin lacus est, molestie vestibulum euismod et, rhoncus et neque. Maecenas venenatis risus sit amet est efficitur sollicitudin. Morbi eu ante id nunc scelerisque ultricies vitae vitae sapien.
            Ut congue tristique lacus quis molestie. Nullam lacus turpis, porta a velit quis, maximus tristique ipsum. Vivamus non pharetra eros. Sed vitae felis dolor. Curabitur et fermentum lacus. Mauris vel malesuada mi. Donec bibendum mauris quis tellus aliquam, ac mattis leo ultricies. Vestibulum metus lacus, scelerisque vel tempus ac, cursus in erat. Sed fermentum justo ac nulla molestie, accumsan malesuada velit ultrices. Morbi condimentum leo id lobortis facilisis. Donec convallis dui ante, at rutrum metus faucibus a. In a sagittis purus, ut euismod nunc.
            Nam eu ipsum diam. Nulla ipsum turpis, euismod eu dolor nec, molestie eleifend tellus. In dictum turpis a sapien dapibus, nec semper libero consequat. Vestibulum ut condimentum massa. Sed eu diam tincidunt lacus luctus bibendum. Mauris sit amet orci nulla. Nulla sed tempor dui. Nulla nunc metus, tincidunt sed mi nec, viverra porttitor mauris. Sed ut lacus quam. Aliquam felis metus, varius in pretium id, lacinia at lacus. Curabitur consequat tellus vel tortor rutrum sollicitudin. Nulla facilisi. Maecenas imperdiet neque vel volutpat imperdiet. Mauris condimentum vulputate vulputate. Praesent feugiat sit amet lectus tincidunt dictum. Aliquam tempor venenatis lorem, sit amet egestas ipsum ullamcorper rhoncus.',
            'slug' => 'parfume-untuk-pria',
            'excerpt' => 'lorem ipsum dolor sit amet constectur lorem ipsum dolor sit amet constectur lorem ipsum dolor sit amet constectur',
            'category_id' => 2
        ]);
        Article::create([
            'title' => 'Parfume Malam hari yang cocok untuk kamu',
            'body' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam eleifend magna id nisi lacinia, et interdum justo egestas. Pellentesque massa arcu, dapibus vel sodales at, aliquam ac tellus. Nulla interdum rhoncus sem ac mollis. Vestibulum quis ex nulla. Morbi et felis et quam pellentesque dapibus ac vitae dolor. In non sapien metus. Sed posuere interdum quam, vitae laoreet neque pellentesque id. Quisque non orci sed neque tincidunt pulvinar eget sed mauris. Vivamus lobortis, nisl lacinia feugiat imperdiet, nunc urna luctus lectus, quis lacinia urna nibh eu magna. Nullam dapibus libero non quam pellentesque, consectetur vulputate quam placerat. Aliquam erat volutpat. Maecenas tincidunt, justo at scelerisque lacinia, arcu nibh ultrices neque, in consectetur eros tellus at orci. In orci magna, auctor in maximus id, tempor vel ipsum.
            In sapien nisl, pellentesque id bibendum vel, maximus a mauris. Curabitur efficitur elementum tincidunt. Nullam feugiat erat sed pretium gravida. Quisque aliquam nunc eros, ac tristique neque sollicitudin ut. Morbi in mi neque. Proin lectus elit, accumsan vel libero id, dictum gravida libero. Cras ultricies et purus laoreet varius. Integer velit dolor, vestibulum ac sagittis non, dapibus lobortis lorem. Cras et ornare magna. Curabitur tincidunt ac libero a lobortis. In hendrerit enim tellus, ac imperdiet lectus volutpat at. Nunc rutrum convallis ligula quis malesuada.
            Aliquam neque ligula, viverra quis metus et, scelerisque auctor leo. Nullam felis mi, ornare et commodo sed, consequat non est. Mauris placerat dignissim elit vel condimentum. Nulla a porta sapien, vitae tristique metus. Fusce iaculis nunc fringilla massa congue pharetra. Nullam eu quam euismod orci dictum bibendum non eget velit. Suspendisse potenti. Cras consequat ex at iaculis tempus. Proin lacus est, molestie vestibulum euismod et, rhoncus et neque. Maecenas venenatis risus sit amet est efficitur sollicitudin. Morbi eu ante id nunc scelerisque ultricies vitae vitae sapien.
            Ut congue tristique lacus quis molestie. Nullam lacus turpis, porta a velit quis, maximus tristique ipsum. Vivamus non pharetra eros. Sed vitae felis dolor. Curabitur et fermentum lacus. Mauris vel malesuada mi. Donec bibendum mauris quis tellus aliquam, ac mattis leo ultricies. Vestibulum metus lacus, scelerisque vel tempus ac, cursus in erat. Sed fermentum justo ac nulla molestie, accumsan malesuada velit ultrices. Morbi condimentum leo id lobortis facilisis. Donec convallis dui ante, at rutrum metus faucibus a. In a sagittis purus, ut euismod nunc.
            Nam eu ipsum diam. Nulla ipsum turpis, euismod eu dolor nec, molestie eleifend tellus. In dictum turpis a sapien dapibus, nec semper libero consequat. Vestibulum ut condimentum massa. Sed eu diam tincidunt lacus luctus bibendum. Mauris sit amet orci nulla. Nulla sed tempor dui. Nulla nunc metus, tincidunt sed mi nec, viverra porttitor mauris. Sed ut lacus quam. Aliquam felis metus, varius in pretium id, lacinia at lacus. Curabitur consequat tellus vel tortor rutrum sollicitudin. Nulla facilisi. Maecenas imperdiet neque vel volutpat imperdiet. Mauris condimentum vulputate vulputate. Praesent feugiat sit amet lectus tincidunt dictum. Aliquam tempor venenatis lorem, sit amet egestas ipsum ullamcorper rhoncus.',
            'slug' => 'parfume-malam-hari-yang-cocok-untuk-kamu',
            'excerpt' => 'lorem ipsum dolor sit amet constectur lorem ipsum dolor sit amet constectur lorem ipsum dolor sit amet constectur',
            'category_id' => 3
        ]);
    }
}
